# Save the output of this file and use kubectl create -f to import
# it into Kubernetes.
#
# Created with podman-5.8.3
apiVersion: v1
kind: Pod
metadata:
  annotations:
    io.kubernetes.cri-o.SandboxID/cross-doc-tool-dev: 2a56a70d4e3f1eb288904b92092266418106fa377c653108cfe7844c800a1a4f
    io.kubernetes.cri-o.SandboxID/dewey-mysql: 2a56a70d4e3f1eb288904b92092266418106fa377c653108cfe7844c800a1a4f
    io.kubernetes.cri-o.SandboxID/dewey-prometheus: 2a56a70d4e3f1eb288904b92092266418106fa377c653108cfe7844c800a1a4f
    io.kubernetes.cri-o.SandboxID/svelte-container: 2a56a70d4e3f1eb288904b92092266418106fa377c653108cfe7844c800a1a4f
  creationTimestamp: "2026-06-26T20:39:10Z"
  labels:
    app: dewey-pod
  name: dewey-pod
spec:
  containers:
  - args:
    - mysqld
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: dewey
    - name: MYSQL_DATABASE
      value: deweyRecords
    image: docker.io/library/mysql:latest
    name: dewey-mysql
    ports:
    - containerPort: 3000
      hostPort: 3000
    - containerPort: 3306
      hostPort: 3306
    - containerPort: 8080
      hostPort: 8080
    - containerPort: 9090
      hostPort: 9090
    volumeMounts:
    - mountPath: /var/lib/mysql
      name: mysql-data-pvc
  - args:
    - --config.file=/etc/prometheus/prometheus.yml
    - --storage.tsdb.path=/prometheus
    image: docker.io/prom/prometheus:latest
    name: dewey-prometheus
    securityContext: {}
    volumeMounts:
    - mountPath: /prometheus
      name: f4f22cd181291112e27b7cd8f84f193432a2e46e7d014d73d11d4353c771ca0c-pvc
  - image: localhost/cross-doc-tool-dev:latest
    name: cross-doc-tool-dev
    securityContext: {}
  - args:
    - /usr/local/bin/node
    - build
    image: localhost/admin-portal:latest
    name: svelte-container
  volumes:
  - name: mysql-data-pvc
    persistentVolumeClaim:
      claimName: mysql-data
  - name: f4f22cd181291112e27b7cd8f84f193432a2e46e7d014d73d11d4353c771ca0c-pvc
    persistentVolumeClaim:
      claimName: f4f22cd181291112e27b7cd8f84f193432a2e46e7d014d73d11d4353c771ca0c

