// Code generated by tui generate. DO NOT EDIT.
// Source: docs_dashboard.gsx

package main

import (
	"fmt"

	tui "github.com/grindlemire/go-tui"
)

type docsDashboard struct {
	source     *tui.State[docsSource]
	scrollY    *tui.State[int]
	contentRef *tui.Ref
}

func DocsDashboard(docName string) *docsDashboard {
	return &docsDashboard{
		source:     tui.NewState(loadDoc(docName)),
		scrollY:    tui.NewState(0),
		contentRef: tui.NewRef(),
	}
}

func (d *docsDashboard) scrollBy(delta int) {
	el := d.contentRef.El()
	if el == nil {
		return
	}
	_, maxY := el.MaxScroll()
	newY := d.scrollY.Get() + delta
	if newY < 0 {
		newY = 0
	} else if newY > maxY {
		newY = maxY
	}
	d.scrollY.Set(newY)
}

func (d *docsDashboard) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.On(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.On(tui.Rune('q'), func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.On(tui.Rune('j'), func(ke tui.KeyEvent) { d.scrollBy(1) }),
		tui.On(tui.Rune('k'), func(ke tui.KeyEvent) { d.scrollBy(-1) }),
		tui.On(tui.KeyDown, func(ke tui.KeyEvent) { d.scrollBy(1) }),
		tui.On(tui.KeyUp, func(ke tui.KeyEvent) { d.scrollBy(-1) }),
	}
}

func (d *docsDashboard) HandleMouse(me tui.MouseEvent) bool {
	switch me.Button {
	case tui.MouseWheelUp:
		d.scrollBy(-1)
		return true
	case tui.MouseWheelDown:
		d.scrollBy(1)
		return true
	}
	return false
}

func (d *docsDashboard) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithHeightPercent(100.00),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithFlexShrink(0),
	)
	__tui_2 := tui.New(
		tui.WithText("Dewey — Docs"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_0.AddChild(__tui_1)
	if d.source.Get().err != nil {
		__tui_3 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
			tui.WithJustify(tui.JustifyCenter),
			tui.WithFlexShrink(0),
		)
		__tui_4 := tui.New(
			tui.WithText(fmt.Sprintf("failed to load doc: %v", d.source.Get().err)),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
		)
		__tui_3.AddChild(__tui_4)
		__tui_0.AddChild(__tui_3)
	} else {
		__tui_5 := tui.New(
			tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
			tui.WithGap(1),
			tui.WithFlexGrow(1.0),
			tui.WithScrollable(tui.ScrollVertical),
			tui.WithScrollOffset(0, d.scrollY.Get()),
		)
		d.contentRef.Set(__tui_5)
		__tui_6 := app.MountPersistent(d, 0, func() tui.Component {
			return tui.NewMarkdown(
				tui.WithMarkdownSource(d.source.Get().content),
			)
		})
		__tui_5.AddChild(__tui_6)
		__tui_0.AddChild(__tui_5)
	}
	__tui_7 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithFlexShrink(0),
	)
	__tui_8 := tui.New(
		tui.WithText("↑/↓ or j/k or mouse wheel to scroll — q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_7.AddChild(__tui_8)
	__tui_0.AddChild(__tui_7)

	return __tui_0
}

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (d *docsDashboard) bindAppFields(app *tui.App) {
	if d.source != nil {
		d.source.BindApp(app)
	}
	if d.scrollY != nil {
		d.scrollY.BindApp(app)
	}
}

func (d *docsDashboard) BindApp(app *tui.App) {
	d.bindAppFields(app)
}

var _ tui.AppBinder = (*docsDashboard)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener   = (*docsDashboard)(nil)
	_ tui.MouseListener = (*docsDashboard)(nil)
)
