// Code generated by tui generate. DO NOT EDIT.
// Source: metrics_dashboard.gsx

package main

import (
	"fmt"
	"time"

	tui "github.com/grindlemire/go-tui"
)

const pollInterval = 5 * time.Second

const sparkHistoryLen = 20

type metricsDashboard struct {
	host             string
	snapshot         *tui.State[metricsSnapshot]
	retrievalHistory *tui.State[[]int]
	rejectionHistory *tui.State[[]int]
	pollCh           chan metricsSnapshot
	scrollY          *tui.State[int]
	contentRef       *tui.Ref
}

func MetricsDashboard(host string) *metricsDashboard {
	pollCh := make(chan metricsSnapshot, 1)
	go pollMetrics(host, pollInterval, pollCh)

	return &metricsDashboard{
		host:             host,
		snapshot:         tui.NewState(metricsSnapshot{}),
		retrievalHistory: tui.NewState([]int{}),
		rejectionHistory: tui.NewState([]int{}),
		pollCh:           pollCh,
		scrollY:          tui.NewState(0),
		contentRef:       tui.NewRef(),
	}
}

func (m *metricsDashboard) applySnapshot(snap metricsSnapshot) {
	m.snapshot.Set(snap)

	pushHistory := func(state *tui.State[[]int], v int) {
		hist := append(append([]int{}, state.Get()...), v)
		if len(hist) > sparkHistoryLen {
			hist = hist[len(hist)-sparkHistoryLen:]
		}
		state.Set(hist)
	}
	pushHistory(m.retrievalHistory, int(snap.scalars["app_file_retrievals"]))
	pushHistory(m.rejectionHistory, int(sumMap(snap.labeled["app_upload_rejections_total"])))
}

func (m *metricsDashboard) Watchers() []tui.Watcher {
	return []tui.Watcher{
		tui.Watch(m.pollCh, m.applySnapshot),
	}
}

func (m *metricsDashboard) scrollBy(delta int) {
	el := m.contentRef.El()
	if el == nil {
		return
	}
	_, maxY := el.MaxScroll()
	newY := m.scrollY.Get() + delta
	if newY < 0 {
		newY = 0
	} else if newY > maxY {
		newY = maxY
	}
	m.scrollY.Set(newY)
}

func (m *metricsDashboard) KeyMap() tui.KeyMap {
	return tui.KeyMap{
		tui.On(tui.KeyEscape, func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.On(tui.Rune('q'), func(ke tui.KeyEvent) { ke.App().Stop() }),
		tui.On(tui.Rune('j'), func(ke tui.KeyEvent) { m.scrollBy(1) }),
		tui.On(tui.Rune('k'), func(ke tui.KeyEvent) { m.scrollBy(-1) }),
		tui.On(tui.KeyDown, func(ke tui.KeyEvent) { m.scrollBy(1) }),
		tui.On(tui.KeyUp, func(ke tui.KeyEvent) { m.scrollBy(-1) }),
	}
}

func (m *metricsDashboard) HandleMouse(me tui.MouseEvent) bool {
	switch me.Button {
	case tui.MouseWheelUp:
		m.scrollBy(-1)
		return true
	case tui.MouseWheelDown:
		m.scrollBy(1)
		return true
	}
	return false
}

func gaugeColor(pct int) string {
	if pct >= 80 {
		return "text-red font-bold"
	}
	if pct >= 60 {
		return "text-yellow"
	}
	return "text-green"
}

func gaugeBar(pct int) string {
	width := 16
	filled := pct * width / 100
	bar := ""
	for i := 0; i < width; i++ {
		if i < filled {
			bar += "█"
		} else {
			bar += "░"
		}
	}
	return bar
}

func sparkline(data []int) string {
	if len(data) == 0 {
		return "(no data yet)"
	}
	blocks := []rune{'▁', '▂', '▃', '▄', '▅', '▆', '▇', '█'}
	maxVal := 1
	for _, v := range data {
		if v > maxVal {
			maxVal = v
		}
	}
	s := ""
	for _, v := range data {
		idx := v * 7 / maxVal
		if idx > 7 {
			idx = 7
		}
		if idx < 0 {
			idx = 0
		}
		s += string(blocks[idx])
	}
	return s
}

func sumMap(m map[string]float64) float64 {
	var total float64
	for _, v := range m {
		total += v
	}
	return total
}

func (m *metricsDashboard) scalar(name string) float64 {
	return m.snapshot.Get().scalars[name]
}

func (m *metricsDashboard) opBytes(op string) float64 {
	return aggregateByOp(m.snapshot.Get().labeled["file_io_bytes_total"])[op]
}

func (m *metricsDashboard) opCount(op string) float64 {
	return aggregateByOp(m.snapshot.Get().labeled["file_io_ops_total"])[op]
}

func (m *metricsDashboard) uploadsByType(fileType string) float64 {
	return m.snapshot.Get().labeled["app_uploads_by_type_total"][fileType]
}

func (m *metricsDashboard) Render(app *tui.App) *tui.Element {
	__tui_0 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithHeightPercent(100.00),
		tui.WithBorder(tui.BorderRounded),
		tui.WithBorderStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_1 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithFlexShrink(0),
	)
	__tui_2 := tui.New(
		tui.WithText("Dewey — Live Metrics"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_1.AddChild(__tui_2)
	__tui_0.AddChild(__tui_1)
	__tui_3 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithFlexShrink(0),
	)
	if m.snapshot.Get().err != nil {
		__tui_4 := tui.New(
			tui.WithText(fmt.Sprintf("unreachable: %v", m.snapshot.Get().err)),
			tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
		)
		__tui_3.AddChild(__tui_4)
	} else {
		__tui_5 := tui.New(
			tui.WithText(fmt.Sprintf("polling %s every %s", m.host, pollInterval)),
			tui.WithTextStyle(tui.NewStyle().Dim()),
		)
		__tui_3.AddChild(__tui_5)
	}
	__tui_0.AddChild(__tui_3)
	__tui_6 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
		tui.WithScrollable(tui.ScrollVertical),
		tui.WithScrollOffset(0, m.scrollY.Get()),
	)
	m.contentRef.Set(__tui_6)
	__tui_7 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexShrink(0),
	)
	__tui_8 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_9 := tui.New(
		tui.WithText("RAM Usage"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_8.AddChild(__tui_9)
	__tui_10 := tui.New(
		tui.WithText(gaugeBar(pctOf(m.scalar("app_ram_usage"), 500))),
	)
	__tui_8.AddChild(__tui_10)
	__tui_11 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f MB", m.scalar("app_ram_usage"))),
	)
	__tui_8.AddChild(__tui_11)
	__tui_7.AddChild(__tui_8)
	__tui_12 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_13 := tui.New(
		tui.WithText("Heap Usage"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_12.AddChild(__tui_13)
	__tui_14 := tui.New(
		tui.WithText(gaugeBar(pctOf(m.scalar("app_heap_usage"), 200))),
	)
	__tui_12.AddChild(__tui_14)
	__tui_15 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f MB", m.scalar("app_heap_usage"))),
	)
	__tui_12.AddChild(__tui_15)
	__tui_7.AddChild(__tui_12)
	__tui_16 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_17 := tui.New(
		tui.WithText("Goroutines"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_16.AddChild(__tui_17)
	__tui_18 := tui.New(
		tui.WithText(gaugeBar(pctOf(m.scalar("go_goroutines"), 200))),
	)
	__tui_16.AddChild(__tui_18)
	__tui_19 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", m.scalar("go_goroutines"))),
	)
	__tui_16.AddChild(__tui_19)
	__tui_7.AddChild(__tui_16)
	__tui_20 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_21 := tui.New(
		tui.WithText("Open FDs"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_20.AddChild(__tui_21)
	__tui_22 := tui.New(
		tui.WithText(gaugeBar(pctOf(m.scalar("process_open_fds"), 100))),
	)
	__tui_20.AddChild(__tui_22)
	__tui_23 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", m.scalar("process_open_fds"))),
	)
	__tui_20.AddChild(__tui_23)
	__tui_7.AddChild(__tui_20)
	__tui_6.AddChild(__tui_7)
	__tui_24 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexShrink(0),
	)
	__tui_25 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_26 := tui.New(
		tui.WithText("Files in Store"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_25.AddChild(__tui_26)
	__tui_27 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", m.scalar("app_files_in_store"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_25.AddChild(__tui_27)
	__tui_24.AddChild(__tui_25)
	__tui_28 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_29 := tui.New(
		tui.WithText("Files in Backup"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_28.AddChild(__tui_29)
	__tui_30 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", m.scalar("app_files_in_backup"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_28.AddChild(__tui_30)
	__tui_24.AddChild(__tui_28)
	__tui_31 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_32 := tui.New(
		tui.WithText("Cache Size"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_31.AddChild(__tui_32)
	__tui_33 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", m.scalar("app_cache_size"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_31.AddChild(__tui_33)
	__tui_24.AddChild(__tui_31)
	__tui_34 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_35 := tui.New(
		tui.WithText("Dumping cache in"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_34.AddChild(__tui_35)
	__tui_36 := tui.New(
		tui.WithText(fmtCountdown(m.scalar("app_time_til_next_tick"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow).Bold()),
	)
	__tui_34.AddChild(__tui_36)
	__tui_24.AddChild(__tui_34)
	__tui_37 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_38 := tui.New(
		tui.WithText("Uptime"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_37.AddChild(__tui_38)
	__tui_39 := tui.New(
		tui.WithText(fmt.Sprintf("%.1f hr", m.scalar("app_uptime_seconds")/3600)),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_37.AddChild(__tui_39)
	__tui_24.AddChild(__tui_37)
	__tui_6.AddChild(__tui_24)
	__tui_40 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexShrink(0),
	)
	__tui_41 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_42 := tui.New(
		tui.WithText("I/O Bytes by Operation"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_41.AddChild(__tui_42)
	__tui_43 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_44 := tui.New(
		tui.WithText("read:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_43.AddChild(__tui_44)
	__tui_45 := tui.New(
		tui.WithText(humanizeBytes(m.opBytes("read"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_43.AddChild(__tui_45)
	__tui_41.AddChild(__tui_43)
	__tui_46 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_47 := tui.New(
		tui.WithText("write:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_46.AddChild(__tui_47)
	__tui_48 := tui.New(
		tui.WithText(humanizeBytes(m.opBytes("write"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta).Bold()),
	)
	__tui_46.AddChild(__tui_48)
	__tui_41.AddChild(__tui_46)
	__tui_40.AddChild(__tui_41)
	__tui_49 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_50 := tui.New(
		tui.WithText("I/O Operation Counts"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_49.AddChild(__tui_50)
	__tui_51 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_52 := tui.New(
		tui.WithText("read ops:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_51.AddChild(__tui_52)
	__tui_53 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", m.opCount("read"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
	)
	__tui_51.AddChild(__tui_53)
	__tui_54 := tui.New(
		tui.WithText("write ops:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_51.AddChild(__tui_54)
	__tui_55 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", m.opCount("write"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
	)
	__tui_51.AddChild(__tui_55)
	__tui_49.AddChild(__tui_51)
	__tui_40.AddChild(__tui_49)
	__tui_6.AddChild(__tui_40)
	__tui_56 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexGrow(1),
	)
	__tui_57 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_58 := tui.New(
		tui.WithText("Activity"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_57.AddChild(__tui_58)
	__tui_59 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_60 := tui.New(
		tui.WithText("File retrievals:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_59.AddChild(__tui_60)
	__tui_61 := tui.New(
		tui.WithText(sparkline(m.retrievalHistory.Get())),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan)),
	)
	__tui_59.AddChild(__tui_61)
	__tui_57.AddChild(__tui_59)
	__tui_62 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_63 := tui.New(
		tui.WithText("Upload rejections:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_62.AddChild(__tui_63)
	__tui_64 := tui.New(
		tui.WithText(sparkline(m.rejectionHistory.Get())),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta)),
	)
	__tui_62.AddChild(__tui_64)
	__tui_57.AddChild(__tui_62)
	__tui_56.AddChild(__tui_57)
	__tui_65 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_66 := tui.New(
		tui.WithText("Upload Activity"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_65.AddChild(__tui_66)
	__tui_67 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_68 := tui.New(
		tui.WithText("Accepted (.jpg):"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_67.AddChild(__tui_68)
	__tui_69 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", m.uploadsByType(".jpg"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
	)
	__tui_67.AddChild(__tui_69)
	__tui_65.AddChild(__tui_67)
	__tui_70 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_71 := tui.New(
		tui.WithText("Accepted (.pdf):"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_70.AddChild(__tui_71)
	__tui_72 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", m.uploadsByType(".pdf"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
	)
	__tui_70.AddChild(__tui_72)
	__tui_65.AddChild(__tui_70)
	__tui_73 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
	)
	__tui_74 := tui.New(
		tui.WithText("Rejected:"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_73.AddChild(__tui_74)
	__tui_75 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", sumMap(m.snapshot.Get().labeled["app_upload_rejections_total"]))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
	)
	__tui_73.AddChild(__tui_75)
	__tui_65.AddChild(__tui_73)
	__tui_56.AddChild(__tui_65)
	__tui_6.AddChild(__tui_56)
	__tui_76 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexShrink(0),
	)
	__tui_77 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_78 := tui.New(
		tui.WithText("Barcode OK"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_77.AddChild(__tui_78)
	__tui_79 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", m.scalar("app_barcode_successes"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Green).Bold()),
	)
	__tui_77.AddChild(__tui_79)
	__tui_76.AddChild(__tui_77)
	__tui_80 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_81 := tui.New(
		tui.WithText("Barcode Fail"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_80.AddChild(__tui_81)
	__tui_82 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", m.scalar("app_barcode_failures"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
	)
	__tui_80.AddChild(__tui_82)
	__tui_76.AddChild(__tui_80)
	__tui_83 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_84 := tui.New(
		tui.WithText("Plugin Runs"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_83.AddChild(__tui_84)
	__tui_85 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", m.scalar("app_plugin_runs"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_83.AddChild(__tui_85)
	__tui_76.AddChild(__tui_83)
	__tui_86 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_87 := tui.New(
		tui.WithText("Plugin Errors"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_86.AddChild(__tui_87)
	__tui_88 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", m.scalar("app_plugin_errors"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
	)
	__tui_86.AddChild(__tui_88)
	__tui_76.AddChild(__tui_86)
	__tui_89 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_90 := tui.New(
		tui.WithText("DB Errors"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_89.AddChild(__tui_90)
	__tui_91 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", m.scalar("app_db_errors"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Red).Bold()),
	)
	__tui_89.AddChild(__tui_91)
	__tui_76.AddChild(__tui_89)
	__tui_92 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_93 := tui.New(
		tui.WithText("Upload Rejections"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_92.AddChild(__tui_93)
	__tui_94 := tui.New(
		tui.WithText(fmt.Sprintf("%.0f", sumMap(m.snapshot.Get().labeled["app_upload_rejections_total"]))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Yellow).Bold()),
	)
	__tui_92.AddChild(__tui_94)
	__tui_76.AddChild(__tui_92)
	__tui_6.AddChild(__tui_76)
	__tui_95 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithGap(1),
		tui.WithFlexShrink(0),
	)
	__tui_96 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_97 := tui.New(
		tui.WithText("Network Receive"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_96.AddChild(__tui_97)
	__tui_98 := tui.New(
		tui.WithText(humanizeBytes(m.scalar("process_network_receive_bytes_total"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Cyan).Bold()),
	)
	__tui_96.AddChild(__tui_98)
	__tui_95.AddChild(__tui_96)
	__tui_99 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Column),
		tui.WithBorder(tui.BorderRounded),
		tui.WithPadding(1),
		tui.WithGap(1),
		tui.WithFlexGrow(1.0),
	)
	__tui_100 := tui.New(
		tui.WithText("Network Transmit"),
		tui.WithTextGradient(tui.NewGradient(tui.Cyan, tui.Magenta).WithDirection(tui.GradientHorizontal)),
		tui.WithTextStyle(tui.NewStyle().Bold()),
	)
	__tui_99.AddChild(__tui_100)
	__tui_101 := tui.New(
		tui.WithText(humanizeBytes(m.scalar("process_network_transmit_bytes_total"))),
		tui.WithTextStyle(tui.NewStyle().Foreground(tui.Magenta).Bold()),
	)
	__tui_99.AddChild(__tui_101)
	__tui_95.AddChild(__tui_99)
	__tui_6.AddChild(__tui_95)
	__tui_0.AddChild(__tui_6)
	__tui_102 := tui.New(
		tui.WithDisplay(tui.DisplayFlex), tui.WithDirection(tui.Row),
		tui.WithJustify(tui.JustifyCenter),
		tui.WithFlexShrink(0),
	)
	__tui_103 := tui.New(
		tui.WithText("↑/↓ or j/k or mouse wheel to scroll — q to quit"),
		tui.WithTextStyle(tui.NewStyle().Dim()),
	)
	__tui_102.AddChild(__tui_103)
	__tui_0.AddChild(__tui_102)

	return __tui_0
}

// updatePropsFields is generated. It copies prop fields from fresh onto
// the receiver. When you override UpdateProps, call this helper instead
// of hand-maintaining the copy list.
func (m *metricsDashboard) updatePropsFields(fresh tui.Component) {
	f, ok := fresh.(*metricsDashboard)
	if !ok {
		return
	}
	m.host = f.host
}

func (m *metricsDashboard) UpdateProps(fresh tui.Component) {
	m.updatePropsFields(fresh)
}

var _ tui.PropsUpdater = (*metricsDashboard)(nil)

// bindAppFields is generated. It wires the component's *tui.App,
// State, Events, and TextArea fields to app. When you override BindApp,
// call this helper instead of hand-maintaining the delegation list.
func (m *metricsDashboard) bindAppFields(app *tui.App) {
	if m.snapshot != nil {
		m.snapshot.BindApp(app)
	}
	if m.retrievalHistory != nil {
		m.retrievalHistory.BindApp(app)
	}
	if m.rejectionHistory != nil {
		m.rejectionHistory.BindApp(app)
	}
	if m.scrollY != nil {
		m.scrollY.BindApp(app)
	}
}

func (m *metricsDashboard) BindApp(app *tui.App) {
	m.bindAppFields(app)
}

var _ tui.AppBinder = (*metricsDashboard)(nil)

// Compile-time interface satisfaction checks.
var (
	_ tui.KeyListener     = (*metricsDashboard)(nil)
	_ tui.MouseListener   = (*metricsDashboard)(nil)
	_ tui.WatcherProvider = (*metricsDashboard)(nil)
)
